const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('playground', {
  checkResources: () => ipcRenderer.invoke('cli:check'),
  toolHelp: id => ipcRenderer.invoke('cli:help', id),
  installTool: id => ipcRenderer.invoke('cli:install', id),
  installMissingTools: () => ipcRenderer.invoke('cli:install-missing'),
  launchCli: value => ipcRenderer.invoke('cli:launch', value),
  vaultStatus: () => ipcRenderer.invoke('vault:status'),
  unlockVault: password => ipcRenderer.invoke('vault:unlock', password),
  onVaultSaveError: callback => { ipcRenderer.on('vault:save-error', () => callback()); },
  readNotebook: () => ipcRenderer.invoke('storage:read'),
  saveNotebook: value => ipcRenderer.invoke('storage:save', value),
  openDataFolder: () => ipcRenderer.invoke('storage:folder'),
  requestExit: () => ipcRenderer.invoke('storage:request-exit'),
  finishExit: () => ipcRenderer.invoke('storage:finish-exit'),
  cancelExit: () => ipcRenderer.invoke('storage:cancel-exit'),
  onPrepareExit: callback => { ipcRenderer.on('storage:prepare-exit', () => callback()); },
  listProfiles: () => ipcRenderer.invoke('profiles:list'),
  addProfile: profile => ipcRenderer.invoke('profiles:add', profile),
  deleteProfile: id => ipcRenderer.invoke('profiles:delete', id),
  setHandoffConsent: value => ipcRenderer.invoke('profiles:set-handoff-consent', value),
  openTask: task => ipcRenderer.invoke('task:open', task),
  exportNotes: notes => ipcRenderer.invoke('file:export', notes),
  importNotes: () => ipcRenderer.invoke('file:import'),
  relayState: () => ipcRenderer.invoke('relay:state'),
  relayLoad: id => ipcRenderer.invoke('relay:load', id),
  relayDelete: id => ipcRenderer.invoke('relay:delete', id),
  relayStart: input => ipcRenderer.invoke('relay:start', input),
  relayResume: input => ipcRenderer.invoke('relay:resume', input),
  relayStop: () => ipcRenderer.invoke('relay:stop'),
  relayRetrySave: () => ipcRenderer.invoke('relay:retry-save'),
  onRelayEvent: callback => { ipcRenderer.on('relay:event', (_event, value) => callback(value)); },
  relayHandoffState: () => ipcRenderer.invoke('relay-handoff:state'),
  setRelayAuto: value => ipcRenderer.invoke('settings:relay-auto', value),
  relayHandoffChoose: id => ipcRenderer.invoke('relay-handoff:choose', id),
  relayHandoffSkip: () => ipcRenderer.invoke('relay-handoff:skip'),
  relayHandoffProceed: () => ipcRenderer.invoke('relay-handoff:proceed'),
  relayHandoffRestartTimer: () => ipcRenderer.invoke('relay-handoff:restart-timer'),
  relayHandoffPause: () => ipcRenderer.invoke('relay-handoff:pause'),
  relayHandoffCancel: () => ipcRenderer.invoke('relay-handoff:cancel'),
  onRelayHandoffEvent: callback => { ipcRenderer.on('relay-handoff:event', (_event, value) => callback(value)); },
  chatState: () => ipcRenderer.invoke('chat:state'),
  chatLoad: id => ipcRenderer.invoke('chat:load', id),
  chatDelete: id => ipcRenderer.invoke('chat:delete', id),
  chatStart: input => ipcRenderer.invoke('chat:start', input),
  chatStop: () => ipcRenderer.invoke('chat:stop'),
  chatRetrySave: () => ipcRenderer.invoke('chat:retry-save'),
  onChatEvent: callback => { ipcRenderer.on('chat:event', (_event, value) => callback(value)); },
  // Automatic web send (app-owned isolated window), unified automatic handoff, CLI seats.
  setAutoContinueConsent: value => ipcRenderer.invoke('profiles:set-auto-continue-consent', value),
  webState: () => ipcRenderer.invoke('web:state'),
  webStart: input => ipcRenderer.invoke('web:start', input),
  webStop: () => ipcRenderer.invoke('web:stop'),
  webRetrySave: () => ipcRenderer.invoke('web:retry-save'),
  webLoad: id => ipcRenderer.invoke('web:load', id),
  webDelete: id => ipcRenderer.invoke('web:delete', id),
  onWebEvent: callback => { ipcRenderer.on('web:event', (_event, value) => callback(value)); },
  handoffState: () => ipcRenderer.invoke('handoff:state'),
  handoffBegin: input => ipcRenderer.invoke('handoff:begin', input),
  handoffChoose: id => ipcRenderer.invoke('handoff:choose', id),
  handoffSkip: () => ipcRenderer.invoke('handoff:skip'),
  handoffProceed: () => ipcRenderer.invoke('handoff:proceed'),
  handoffRestartTimer: () => ipcRenderer.invoke('handoff:restart-timer'),
  handoffPause: () => ipcRenderer.invoke('handoff:pause'),
  handoffCancel: () => ipcRenderer.invoke('handoff:cancel'),
  markExhausted: id => ipcRenderer.invoke('handoff:mark-exhausted', id),
  rejoinProfile: id => ipcRenderer.invoke('handoff:rejoin', id),
  onHandoffEvent: callback => { ipcRenderer.on('handoff:event', (_event, value) => callback(value)); },
  setSettings: value => ipcRenderer.invoke('settings:set', value),
  seatLogin: id => ipcRenderer.invoke('seat:login', id),
  seatStatus: id => ipcRenderer.invoke('seat:status', id),
  seatCredentialStatus: id => ipcRenderer.invoke('seat:credential-status', id),
  seatCredentialAction: (id, action) => ipcRenderer.invoke('seat:credential-action', typeof id === 'object' ? id : { id, action }),
  appInfo: () => ipcRenderer.invoke('app:info'),
  setMainReady: () => ipcRenderer.invoke('main:ready'),
  // 휴대용 자체 업데이트(Windows x64): 렌더러는 확인·동의 창·적용·취소만 요청하며 주소·경로를 넘기지 않는다.
  checkUpdate: opts => ipcRenderer.invoke('updater:check', { startup: Boolean(opts && opts.startup) }),
  offerUpdate: () => ipcRenderer.invoke('updater:offer'),
  applyUpdate: () => ipcRenderer.invoke('updater:apply'),
  cancelUpdate: () => ipcRenderer.invoke('updater:cancel'),
  updateStatus: () => ipcRenderer.invoke('updater:status'),
  startupUpdateResult: () => ipcRenderer.invoke('updater:startup-result'),
  onUpdateProgress: callback => { ipcRenderer.on('updater:progress', (_event, value) => callback(value)); }
});
